hadoop_version: 3.3.0

ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEAsUZ3u/9uEDW488hgV45abyIDjv7j6Yw40EQ4+AdL6EGxkcKWZwbx
  GSEIxKf4Dnx7zK8je7Vs6VXdVyu+GXIVeiBlB3E88siCYfLF7+0Ib6KQ8yeIJdnV+7tSGC
  LmpH6EmV/IC7rXxuLGkVmd4phayFo9eF31DhVaA4vqT8VHk4XSEIyAx5hn5IU9sQCc3oLx
  sRk/VXIK79thhc4HpTeo49agwkgLkBQZ++KJGrAkHNl5esdvdDW82x7BDOnVBDmg4xeUPz
  d3upL7Djb+5zkN9tFEW5J+OAoWNNSjEsGS/kQLl7cCTs32m4q+eh51S2ak7fblXzHniXi3
  HI14Jy9mn6ekd89l7H95QEOSecqCK4CrkAbWPKYeTOu8lphun1aB7yzxPI6Rn2T4RPWbb8
  nCoHtSV1Vp2ly5/xwtI9xZnloBKd1WMk2Hpe6PzbcgSrDe7cZ8FCeETDoEw8UIB4Q4bJaE
  Heesi4vhal+3r0XrgC2Gt9uB9Ifi20CUifA6qsBlAAAFoDL1Gioy9RoqAAAAB3NzaC1yc2
  EAAAGBALFGd7v/bhA1uPPIYFeOWm8iA47+4+mMONBEOPgHS+hBsZHClmcG8RkhCMSn+A58
  e8yvI3u1bOlV3VcrvhlyFXogZQdxPPLIgmHyxe/tCG+ikPMniCXZ1fu7Uhgi5qR+hJlfyA
  u618bixpFZneKYWshaPXhd9Q4VWgOL6k/FR5OF0hCMgMeYZ+SFPbEAnN6C8bEZP1VyCu/b
  YYXOB6U3qOPWoMJIC5AUGfviiRqwJBzZeXrHb3Q1vNsewQzp1QQ5oOMXlD83d7qS+w42/u
  c5DfbRRFuSfjgKFjTUoxLBkv5EC5e3Ak7N9puKvnoedUtmpO325V8x54l4txyNeCcvZp+n
  pHfPZex/eUBDknnKgiuAq5AG1jymHkzrvJaYbp9Wge8s8TyOkZ9k+ET1m2/JwqB7UldVad
  pcuf8cLSPcWZ5aASndVjJNh6Xuj823IEqw3u3GfBQnhEw6BMPFCAeEOGyWhB3nrIuL4Wpf
  t69F64AthrfbgfSH4ttAlInwOqrAZQAAAAMBAAEAAAGBAJFyKYa7WYg/K5IIUtNDXntTwu
  utwTy66Vomvz7wbZ0PWSsoJdI95c4iRlljHqh0Bfa3szsqbUM8Sa/dmciyy2A59+oVRFZF
  oIPQdgoVxhghnx+AzbmQcnppBD/9UpKfoxdbeHv3PlZVdWmHx3xEWCeNsmVxYT++0O2b/B
  Ca4dDtuJ4PSRF5v7PEhgsVX59IfBg7iLUILmUA75Ciq68obY8RZzA/gA0kEPWStb6JyfdJ
  jtvniVAlTt/Q6b84kqc2x6XuJTXAjrRcXO2+Gnx+PB0tTUkua+ri9F9E3pYOK9C3wYd974
  jwmZtgWe+6pl4mePQsttS9d8NErrEuQCeCloV2A7WariNtAuMAuzBWOs7Tnpv2rViQvsuD
  fsP5VvoVmeB4LYOuIHg5UHch1wz+o82vGptO4+JCE+0RKzRfeYIazRGCfL6YSeVoOhE2vB
  Dzd5UkTtaptg3YrhSHAQYMXOVGiJrngKPZy7acLkN6sleDpC19i2OlMadh84ssdB/a+QAA
  AMBLbh6xTXhDWF+bGYUxG/cvyzaDS075Fp7f4oYBn8kxgnCp3Kk+eI99CLVLekiHqiw55k
  S4sKBrOIfDU2Wcfnwyrp0UpTtN74QGyPygx4ydtPZWOcUuSfsTAQSW49lo5vXWS4TYs1yP
  1S53ESkGbD5tgZnupEw7aBycI2UruZOwBViyn9yYdsAh7S/nOqq3FCgUtVBWwlMzoageg7
  uD9Z4D1CgtQVdO1gF08nJFlc2Uet200xUKohtN3rhfUUArXeQAAADBAN3nQS81wClXz9FR
  RMETibs03XqeX56jDNUnlQGNtYmYUiZjaadFqAQfL2MfwDgpxXYhPfl0cjRe2PjUiy3HXh
  wZG6xYNOyouI+HnAeCT1HHuNKHJo+ONcQvI43jreQWbBlYR9cccQq+t/+WtVCdsLX/yCWG
  6OYHv9tDTCs8a/YB1iWeqmznt9yX//rgr0lL28eEQXL4qG0WJBDKtmIw8xgx62XAEI5t6o
  lcLWPBvqmMR4xQFJF4ktQL6UD/JF4COwAAAMEAzIO7aj+ILmgFZZSDORn7gjqqW+6evZdz
  P4rwLFFYjWutkBD0yRZkaoYg8rGzv24py0cdHIiA/lCoYPawVFt7qeZDzMcccNdI0T6JmE
  v5MvORjP81arIe7Dsp1CJndJ9kPUmSyDg5GSZM1oOAMaMI1wPk3veiHT0iD3vdwUKmqczA
  ErX9jPv2XJiK4mIiFpo1mpSYQVTi8GjdgOVwcdBgWtxzdljvh1Y935OV4Bpnuy/7y9l3Oi
  GeB6ooN95mEH3fAAAAJWFrb25kcmF0ZXZATWFjQm9vay1Qcm8tYWRtaWNpdHkubG9jYWwB
  AgMEBQ==
  -----END OPENSSH PRIVATE KEY-----

ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxRne7/24QNbjzyGBXjlpvIgOO/uPpjDjQRDj4B0voQbGRwpZnBvEZIQjEp/gOfHvMryN7tWzpVd1XK74ZchV6IGUHcTzyyIJh8sXv7QhvopDzJ4gl2dX7u1IYIuakfoSZX8gLutfG4saRWZ3imFrIWj14XfUOFVoDi+pPxUeThdIQjIDHmGfkhT2xAJzegvGxGT9Vcgrv22GFzgelN6jj1qDCSAuQFBn74okasCQc2Xl6x290NbzbHsEM6dUEOaDjF5Q/N3e6kvsONv7nOQ320URbkn44ChY01KMSwZL+RAuXtwJOzfabir56HnVLZqTt9uVfMeeJeLccjXgnL2afp6R3z2Xsf3lAQ5J5yoIrgKuQBtY8ph5M67yWmG6fVoHvLPE8jpGfZPhE9ZtvycKge1JXVWnaXLn/HC0j3FmeWgEp3VYyTYel7o/NtyBKsN7txnwUJ4RMOgTDxQgHhDhsloQd56yLi+FqX7evReuALYa324H0h+LbQJSJ8DqqwGU="